[deploy]
restartPolicyType = "NEVER"
healthcheckPath = "/health"
healthcheckTimeout = 600
startCommand = "uvicorn src.simple_api:app --host 0.0.0.0 --port $PORT"
buildCommand = "pip install -r requirements.txt"
