services:
  - type: web
    name: crop-yield-prediction-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: LOG_LEVEL
        value: INFO
    plan: starter
    healthCheckPath: /health
    autoDeploy: true
    # Optional: Add custom domain
    # customDomains:
    #   - api.yourdomain.com
