services:
  - type: web
    name: crop-yield-prediction-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
    plan: starter
    healthCheckPath: /health
